In [1]:
import numpy as np
import pandas as pd

In [6]:
f01 = pd.read_excel("excel/學生第一學期分數.xlsx")

In [8]:
f02 = f01[['學號', '國文', '英文', '數學', '歷史', '地理']]
f02

    學號  國文  英文  數學  歷史  地理
0   19  85  56  91  89  99
1   44  73  82  89  84  91
2   22  94  75  77  85  87
3   42  69  78  89  75  96
4   34  92  54  87  74  92
5    4  67  90  95  76  70
6   24  93  93  67  48  95
7   21  71  99  64  84  66
8    9  58  78  62  88  96
9   30  79  97  42  90  70
10  12  80  59  92  70  73
11  41  63  96  95  67  53
12   2  90  48  93  60  82
13   3  96  81  72  66  57
14  48  43  60  80  81  95
15   5  84  72  86  63  53
16  29  45  96  77  97  43
17   7  85  56  59  97  60
18  17  61  42  95  88  71
19  50  48  58  72  92  85
20   6  88  71  79  53  63
21  33  52  59  93  55  90
22  16  99  46  41  71  91
23  32  57  73  88  76  54
24  36  68  55  77  61  83
25  37  47  96  80  67  52
26  20  91  89  69  47  43
27  43  80  54  58  91  54
28  14  56  42  81  87  65
29  26  91  41  65  70  61
30   8  47  75  65  94  45
31  10  70  78  89  40  47
32  49  82  42  42  89  62
33  47  45  88  94  40  48
34  38  80  49  60  72  53
35  23  75  52  80  44  62
36  31  44  55  73  66  73
37  25  52  61  92  53  52
38  13  78  62  53  64  52
39  35  47  53  42  89  78
40  28  96  46  65  59  40
41  11  51  80  68  45  62
42  39  88  77  47  43  47
43  27  95  43  56  43  55
44  18  49  45  61  78  44
45  15  53  41  88  54  41
46  40  41  49  76  58  50
47  46  68  58  66  42  40
48   1  50  48  40  71  64
49  45  49  50  41  63  56

In [17]:
def description(s:pd.Series)->pd.Series:
    max = s.max()
    ind_max= s[s == max].index[0]
    min = s.min()
    ind_min= s[s == min].index[0]
    std = s.std();
    return pd.Series([ind_max, max,ind_min, min, std], index=['最高科目', '最高', '最低科目','最低', '標準差'])

In [18]:
f03 = f02.set_index('學號')
f03

    國文  英文  數學  歷史  地理
學號
19  85  56  91  89  99
44  73  82  89  84  91
22  94  75  77  85  87
42  69  78  89  75  96
34  92  54  87  74  92
4   67  90  95  76  70
24  93  93  67  48  95
21  71  99  64  84  66
9   58  78  62  88  96
30  79  97  42  90  70
12  80  59  92  70  73
41  63  96  95  67  53
2   90  48  93  60  82
3   96  81  72  66  57
48  43  60  80  81  95
5   84  72  86  63  53
29  45  96  77  97  43
7   85  56  59  97  60
17  61  42  95  88  71
50  48  58  72  92  85
6   88  71  79  53  63
33  52  59  93  55  90
16  99  46  41  71  91
32  57  73  88  76  54
36  68  55  77  61  83
37  47  96  80  67  52
20  91  89  69  47  43
43  80  54  58  91  54
14  56  42  81  87  65
26  91  41  65  70  61
8   47  75  65  94  45
10  70  78  89  40  47
49  82  42  42  89  62
47  45  88  94  40  48
38  80  49  60  72  53
23  75  52  80  44  62
31  44  55  73  66  73
25  52  61  92  53  52
13  78  62  53  64  52
35  47  53  42  89  78
28  96  46  65  59  40
11  51  80  68  45  62
39  88  77  47  43  47
27  95  43  56  43  55
18  49  45  61  78  44
15  53  41  88  54  41
40  41  49  76  58  50
46  68  58  66  42  40
1   50  48  40  71  64
45  49  50  41  63  56

In [19]:
f03.apply(description, axis= 1)

   最高科目  最高 最低科目  最低        標準差
學號
19   地理  99   英文  56  16.462078
44   地理  91   國文  73   7.049823
22   國文  94   英文  75   7.733046
42   地理  96   國文  69  10.922454
34   國文  92   英文  54  16.192591
4    數學  95   國文  67  12.340989
24   地理  95   歷史  48  20.933227
21   英文  99   數學  64  14.652645
9    地理  96   國文  58  16.334014
30   英文  97   數學  42  21.431286
12   數學  92   英文  59  12.235195
41   英文  96   地理  53  19.575495
2    數學  93   英文  48  19.692638
3    國文  96   地理  57  14.909728
48   地理  95   國文  43  20.364184
5    數學  86   地理  53  13.974978
29   歷史  97   地理  43  26.434826
7    歷史  97   英文  56  18.447222
17   數學  95   英文  42  21.243823
50   歷史  92   國文  48  18.275667
6    國文  88   歷史  53  13.608821
33   數學  93   國文  52  19.992499
16   國文  99   數學  41  25.976913
32   數學  88   地理  54  14.081903
36   地理  83   英文  55  11.410521
37   英文  96   國文  47  20.156885
20   國文  91   地理  43  22.565460
43   歷史  91   英文  54  17.052859
14   歷史  87   英文  42  18.322118
26   國文  91   英文  41  17.966636
8    歷史  94   地理  45  20.400980
10   數學  89   歷史  40  20.729206
49   歷史  89   英文  42  21.904337
47   數學  94   歷史  40  25.806976
38   國文  80   英文  49  12.988456
23   數學  80   歷史  44  15.126136
31   數學  73   國文  44  12.557866
25   數學  92   國文  52  17.190113
13   國文  78   地理  52  10.497619
35   歷史  89   數學  42  20.559669
28   國文  96   地理  40  21.856349
11   英文  80   歷史  45  13.845577
39   國文  88   歷史  43  20.610677
27   國文  95   英文  43  21.396261
18   歷史  78   地理  44  14.328294
15   數學  88   英文  41  19.269146
40   數學  76   國文  41  13.292855
46   國文  68   地理  40  13.160547
1    歷史  71   數學  40  12.601587
45   歷史  63   數學  41   8.228001

In [20]:
f03.apply(description, axis= 0)

             國文         英文         數學         歷史         地理
最高科目  16.000000  21.000000   4.000000  29.000000  19.000000
最高    99.000000  99.000000  95.000000  97.000000  99.000000
最低科目  40.000000  26.000000   1.000000  10.000000  28.000000
最低    41.000000  41.000000  40.000000  40.000000  40.000000
標準差   18.287109  18.151247  17.047126  17.090026  17.933312

In [16]:
s = f03.iloc[0]
display(s[s==s.max()].index[0])

'地理'